name: 'Google Drive File Action'
description: 'Upload or download files from Google Drive'
author: 'Your Name'
inputs:
  action:
    description: 'Action to perform: upload or download'
    required: true
  filename:
    description: 'Path to the file to upload or download'
    required: true
  name:
    description: 'Name of the file on Google Drive'
    required: false
  folder_id:
    description: 'ID of the file on Google Drive (for download action)'
    required: false
  drive_id:
    description: 'ID of the folder on Google Drive to upload the file to (for upload action)'
    required: true
  credentials_file:
    description: 'Path to the credentials file (Base64 encoded Google service account credentials)'
    required: true
  overwrite:
    description: 'Boolean indicating whether to overwrite existing files (for upload action)'
    required: false
    default: 'false'
  # encoded:
  #   description: 'Boolean indicating whether the filename is encoded (for download action)'
  #   required: true
  #   default: 'true'
outputs:
  download_path:
    description: 'Path to the downloaded file (for download action)'
runs:
  using: "docker"
  image: "Dockerfile"