name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run action
        uses: YoYoGames/Gdrive-Actions@main # Use the action in the current repository
        with:
          action: 'upload' 
          filename: 'RoboHelpTool-2024.2.0.zip'
          folder_id: ${{ secrets.FOLDER_ID }} # If available
          drive_id: '${{ secrets.DRIVE_ID }}' # If available
          credentials_file: ${{ secrets.CREDENTIALS_FILE }}

