name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        CREDENTIALS_FILE: ${{ secrets.CREDENTIALS_FILE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run action
        uses: YoYoGames/Gdrive-Actions@main # Use the action in the current repository
        with:
          action: 'download' 
          filename: 'RoboHelpTool-2024.2.0.zip'
          folder_id: ${{ secrets.FOLDER_ID }} # If available
          drive_id: '${{ secrets.DRIVE_ID }}' # If available
          name: 'RoboHelpTool-2024.2.0.zip'
          credentials_file: ${{ env.CREDENTIALS_FILE }}


